# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - make generate

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  - 386
  - arm64
  goos:
  - linux
  - darwin
  goarm:
  - 7
  binary: gsync

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

signs:
- artifacts: checksum
  args: ["-u", "4E74BD9589869F6CB8A73D279533207D7E3143FC", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
- extra_files:
  - docker/entrypoint.sh
  image_templates:
  - "ghcr.io/ccremer/greposync:v{{ .Version }}"

    # For prereleases, updating `latest` and the floating tags of the major version does not make sense.
    # Only the image for the exact version should be pushed.
  - "{{ if not .Prerelease }}ghcr.io/ccremer/greposync:v{{ .Major }}{{ end }}"
  - "{{ if not .Prerelease }}ghcr.io/ccremer/greposync:latest{{ end }}"

nfpms:
- vendor: ccremer
  homepage: https://github.com/ccremer/greposync
  maintainer: ccremer
  description: ModuleSync reimplemented in Go with extras
  license: Apache 2.0
  file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  formats:
  - deb
  - rpm
  - apk

release:
  prerelease: auto
