# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux
  binary: gsync

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

# signs:
# - artifacts: checksum
#   args: ["-u", "3E0B9A63FF344E7CB445BD84ED35499391B64DB4", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
- image_templates:
  - "quay.io/ccremer/greposync:v{{ .Version }}"

    # For prereleases, updating `latest` and the floating tags of the major version does not make sense.
    # Only the image for the exact version should be pushed.
  - "{{ if not .Prerelease }}quay.io/ccremer/greposync:v{{ .Major }}{{ end }}"
  - "{{ if not .Prerelease }}quay.io/ccremer/greposync:latest{{ end }}"

nfpms:
- vendor: ccremer
  homepage: https://github.com/ccremer/greposync
  maintainer: ccremer
  description: ModuleSync reimplemented in Go with extras
  license: Apache 2.0
  file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  formats:
  - deb
  - rpm
  - apk

release:
  prerelease: auto
  github:
    owner: ccremer
    name: greposync
