git:
  commitBranch: greposync-update
  commitMessage: Update from greposync
  defaultNamespace: github.com
  forcePush: false
  root: repos
log:
  showDiff: false
  showLog: false
pr:
  body: This Pull request updates this repository with changes from a greposync template
    repository.
  create: false
  labels: []
  subject: Update from greposync
  targetBranch: ""
template:
  root: template
