site:
  title: greposync docs
  start_page: greposync::index.adoc
  url: https://ccremer.github.io/greposync
content:
  sources:
    - url: ../
      branches:
        - HEAD
        - docs/v*
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: public/
  clean: true
asciidoc:
  attributes:
    gh-owner: ccremer
    gh-repo: greposync
